[package]
authors = ["roadup <roadup.cc@gmail.com>"]
edition = "2021"
name = "edon"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"
colored = "2.0.0"
console-subscriber = "0.1.8"
env_logger = "0.10"
futures = "0.3.6"
log = "0.4.17"
queues = "1.0.2"
quote = "1.0"
regex = "1"
relative-path = "1.8.0"
reqwest = { version = "0.11.14", features = ["blocking"] }
serde_json = "1.0.99"
serde_v8 = "0.126.0"
swc = "0.266.20"
swc_common = { version = "0.32.1", features = ["tty-emitter"] }
swc_ecma_ast = "0.109.1"
swc_ecma_parser = "0.140.0"
swc_ecma_visit = "0.95.1"
swc_ecma_transforms_module = "0.176.14"
url = "2.3.1"
v8 = "0.78.0"
anyhow = "1.0.71"
tracing = "0.1.37"

[dependencies.tokio]
features = ["full"]
version = "1.19.2"
